---
- name: Create /etc/skel
  file:
    path: /etc/skel
    state: directory
    mode: '0755'
  tags: packages

- name: grml
  get_url:
    url: https://raw.githubusercontent.com/grml/grml-etc-core/master/etc/zsh/zshrc
    dest: /etc/skel/.zshrc
    mode: '0644'
  tags: packages

- name: Set timezone
  timezone:
    name: "{{ vm_timezone }}"
  tags: timezone
