---
- name: Create /etc/skel
  file:
    path: /etc/skel
    state: directory
    mode: '0755'
  tags: packages

- name: grml
  get_url:
    url: https://raw.githubusercontent.com/grml/grml-etc-core/master/etc/zsh/zshrc
    dest: /etc/skel/.zshrc
    mode: '0644'
  tags: packages

- name: Set timezone
  timezone:
    name: "{{ vm_timezone }}"
  tags: timezone

- name: Disable SSH password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    validate: '/usr/sbin/sshd -t -f %s'
  notify: restart sshd
  when: vm_ssh_disable_password_auth | bool
  tags: ssh
