---
- name: upgrade all packages
  dnf:
    name: "*"
    state: latest
  tags: packages

- name: autoremove
  dnf:
    autoremove: yes
  tags: packages

- name: Install qemu-guest-agent
  dnf:
    name: qemu-guest-agent
    state: present
  tags: proxmox-agent

- name: Enable and start qemu-guest-agent
  service:
    name: qemu-guest-agent
    state: started
    enabled: yes
  tags: proxmox-agent

- name: install dependencies base with dnf
  dnf:
    name: "{{ fedora_packages }}"
    state: present
  tags: packages

- name: Install locale langpacks
  dnf:
    name: "{{ vm_locales | map('regex_replace', '^([a-z]+)_.*', 'glibc-langpack-\\1') | list }}"
    state: present
  tags: locale

- name: Set system locale
  copy:
    dest: /etc/locale.conf
    content: "LANG={{ vm_locales[0] }}\n"
  tags: locale
