---
- import_tasks: dnf.yml
  when: ansible_distribution == "Fedora"

- import_tasks: apt.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- import_tasks: apk.yml
  when: ansible_distribution == "Alpine"

- import_tasks: common.yml
